### PR TITLE
first ue4.24 support (virtual textures)

### PR DESCRIPTION
**Pull request by FunGamesLeaks**
Hey, created a short fix for the ue4.24 virtual textures so that the viewer will be able to open fortnites files again

### CODE REVIEW

**Comment by FunGamesLeaks** [comment]
Sorry messed something up the VER_UE4_24 needs to get a new version number, old textures won't load with this anymore

**Comment by gildor2** [comment]
I've made fixes for https://www.gildor.org/smf/index.php/topic,6846.0.html
It appears to be the same as in this PR, so I guess VirtualTexture feature appeared in UE4.23 rather than in UE4.24.

**Comment by FunGamesLeaks** [comment]
Possible, I just saw that it the game updated to UE 4.24 and with that the texture changes came in

**Comment by gildor2** [comment]
I've verified many things just a few minutes ago. Fortnite DIDN'T use UE4.23 - it was on UE4.24 for months. This added a lot of mess with "real" UE4.23.

**Comment by FunGamesLeaks** [comment]
Ok, sorry then

**Comment by gildor2** [comment]
Absolutely not a problem :)

**Pull request closed without merging**
